name: LDP Builder

on: [push]

env:
  LDPHOST: 152.19.134.151
  LDPPORT: 122
  LDPUSER: builder

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: ðŸ” Building System Preparation 
      run: |
        sudo apt update
        sudo apt -y install texlive-font-utils linuxdoc-tools-text linuxdoc-tools-latex docbook-dsssl docbook-xsl docbook-utils htmldoc htmldoc-common docbook-xsl html2text docbook5-xml docbook-xsl-ns jing asciidoc libxml2-utils python3-stdeb fakeroot python3-all python3-networkx python3-nose fop ldp-docbook-xsl ldp-docbook-dsssl docbook opensp dh-python
      shell: bash

    - name: Restoring Martins LDP Python Scripts from Cache
      uses: actions/cache@v1
      with:
        path: python-tldp/deb_dist
        key: python-tldp

    - name: ðŸ§± Compiling Martins LDP Python Scripts if not Found in Cache
      if: steps.python-tldp.outputs.cache-hit != 'true'
      run: |
        cd ~/work
        git clone https://github.com/tLDP/python-tldp
        cd python-tldp && rm -rf debian
        python3 setup.py --command-packages=stdeb.command bdist_deb
      shell: bash

    - name: Installation of Martins LDP Python Scripts
      run: |
        cd ~/work
        sudo dpkg -i python-tldp/deb_dist/python3-tldp_*_all.deb
        ldptool --dump-cfg
      shell: bash

    - name: ðŸ”€ Restoring SSH Key to Manage Documentation Repository
      run: |
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        echo "$SSH_KEY" > ~/.ssh/ldpkey
        chmod 400 ~/.ssh/ldpkey
        ssh-keyscan -p $LDPPORT -H $LDPHOST >> ~/.ssh/known_hosts
      shell: bash
      env:
        SSH_KEY: ${{secrets.SSHK}}

#    - name: Restoring Production (Master Branch) LDP Docs from Cache
#      uses: actions/cache@v1
#      with:
#        path: MAIN
#        key: ldpdocs-main

#    - name: ðŸ”€ Restoring Production (Master Branch) LDP Docs from LDP WWW Server
#      run: |
#        cd ~/work
#        mkdir -p MAIN
#        mkdir -p TMP
#        rsync --stats -rvclz --delete-before -e "ssh -p $LDPPORT -i ~/.ssh/ldpkey" $LDPUSER@$LDPHOST:/home/builder/build/en/ TMP/en
#      shell: bash

    - name: ðŸ§± LDP Documents Processing via Martins scripts
      run: |
        cd ~/work
        mkdir -p BUILD
        mkdir -p MAIN
        ls -alR
        ldptool --loglevel info --builddir BUILD --configfile LDP/.github/builder.ldptool.cfg --pubdir MAIN --list
        ldptool --loglevel info --builddir BUILD --configfile LDP/.github/builder.ldptool.cfg --pubdir MAIN --publish
      shell: bash

#    - name: ðŸ”€ Built Documents Transfer for Master
#      run:
#        rsync --stats -rvclz --delete-before -e 'ssh -p $LDPPORT -i ~/.ssh/ldpkey' MAIN/en/ $LDPUSER@$LDPHOST:/home/builder/build/en
#      shell: bash

# happy end.
